%define CONFIG_GPL 1
%define ARCH_X86 1
%define ARCH_IA64 0
%define ARCH_SPARC 0
%define ARCH_ARM 0
%define ARCH_AVR32 0
%define ARCH_SH4 0
%define ARCH_PPC 0
%define ARCH_ALPHA 0
%define ARCH_MIPS 0
%define ARCH_PA_RISC 0
%define ARCH_S390 0
%define ARCH_S390X 0
%define ARCH_VAX 0
%define ARCH_BFIN 0
%define ARCH_XTENSA 0
%define ARCH_TOMI 0
%define ARCH_GENERIC 0
%define ARCH_X86_32 1
%define ARCH_X86_64 0
%define ARCH_PPC64 0
%define HAVE_ALTIVEC 0
%define HAVE_AVX 0
%define HAVE_MMX 0
%define HAVE_MMX2 0
%define HAVE_AMD3DNOW 0
%define HAVE_AMD3DNOWEXT 0
%define HAVE_SSE 0
%define HAVE_SSE2 0
%define HAVE_SSSE3 0
%define HAVE_FAST_CMOV 0
%define HAVE_CMOV 0
%define HAVE_FAST_CLZ 1
%define HAVE_ARMV5TE 0
%define HAVE_ARMV6 0
%define HAVE_ARMV6T2 0
%define HAVE_ARMVFP 0
%define HAVE_VFPV3 0
%define HAVE_NEON 0
%define HAVE_IWMMXT 0
%define HAVE_MMI 0
%define HAVE_VIS 0
%define HAVE_MVI 0
